# docker-compose.yml
version: '3.4'
services:
  nomad-vnc:
    image: nomad-vnc
    build:
      context: ./nomad-vnc
      dockerfile: Dockerfile
      args: # all envvars can be taken from .env
        - UserName=${UserName}
        - Uid=${Uid}
        - Gid=${Gid}
        - VNCNumber=${VNCNumber}
        - VNCPort=${VNCPort}
        - VNCPassword="${VNCPassword}"
    user: ${UserName}
    stdin_open: true
    tty: true
    volumes:
      - "${IO}:/io:rw"
      - type: tmpfs
        target: /tmp
    network_mode: host # docker container shares the host network
